apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dukqa-platform-admin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dukqa-platform-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dukqa-platform-admin
subjects:
- kind: ServiceAccount
  name: dukqa-platform-admin
  namespace: ec2-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dukqa-platform-admin
  namespace: ec2-apps
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746387399274:role/DukQaPlatformAdminRole