apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: argocd
type: Opaque
data:
  access-key-id: <base64-encoded-access-key>
  secret-access-key: <base64-encoded-secret-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
type: Opaque
data:
  username: <base64-encoded-github-username>
  password: <base64-encoded-github-token>
---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-credentials
  namespace: ec2-apps
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: ec2-apps
type: Opaque
data:
  host: <base64-encoded-db-host>
  username: <base64-encoded-db-username>
  password: <base64-encoded-db-password>
  database: <base64-encoded-db-name>