apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746387399274:role/secrets-store-csi-role-dukqa-platform
