apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: dukqa-platform
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.1
    helm:
      values: |
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::746387399274:role/argocd-image-updater-role
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        config:
          registries:
            - name: ecr
              api_url: https://746387399274.dkr.ecr.eu-west-1.amazonaws.com
              prefix: 746387399274.dkr.ecr.eu-west-1.amazonaws.com
              ping: yes
              credentials: ext:/scripts/auth1.sh
          logLevel: info
          argocd:
            serverAddress: argocd-server.argocd.svc.cluster.local:443
            insecure: false
        authScripts:
          enabled: true
          scripts:
            auth1.sh: |
              #!/bin/sh
              aws ecr get-login-password --region eu-west-1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true