apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dukqa-platform
  namespace: argocd
spec:
  description: DukQa Platform Project
  sourceRepos:
  - 'https://github.com/dukqa-org/dukqa-platform'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://argoproj.github.io/argo-helm'
  destinations:
  - namespace: dukqa-apps
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: infra
    server: https://kubernetes.default.svc
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: PersistentVolume
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: storage.k8s.io
    kind: StorageClass
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionWebhook
  - group: admissionregistration.k8s.io
    kind: MutatingAdmissionWebhook
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: DaemonSet
  - group: networking.k8s.io
    kind: Ingress
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  - group: batch
    kind: Job
  - group: batch
    kind: CronJob
  - group: extensions
    kind: '*'
  - group: policy
    kind: '*'
  - group: secrets-store.csi.x-k8s.io
    kind: SecretProviderClass
  - group: external-secrets.io
    kind: '*'
  - group: monitoring.coreos.com
    kind: '*'
  - group: argoproj.io
    kind: '*'
  roles:
  - name: admin
    description: Admin role for DukQa Platform
    policies:
    - p, proj:dukqa-platform:admin, applications, *, dukqa-platform/*, allow
    - p, proj:dukqa-platform:admin, repositories, *, *, allow
    groups:
    - dukqa-platform:admin