apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secrets-store-provider-aws
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: secrets-store-provider-aws
  template:
    metadata:
      labels:
        app: secrets-store-provider-aws
    spec:
      serviceAccountName: secrets-store-csi-driver
      containers:
      - name: provider-aws-installer
        image: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-50-g5b4aca1-2023.06.09.21.19
        args:
        - --provider-volume=/etc/kubernetes/secrets-store-csi-providers

        securityContext:
          privileged: true
        volumeMounts:
        - name: providervol
          mountPath: /etc/kubernetes/secrets-store-csi-providers
        - name: mountpoint-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
      volumes:
      - name: providervol
        hostPath:
          path: /etc/kubernetes/secrets-store-csi-providers
          type: DirectoryOrCreate
      - name: mountpoint-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
      tolerations:
      - operator: Exists