apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: document-upload-hpa
  namespace: dukqa-apps
  labels:
    app: document-upload-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: document-upload-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65

