apiVersion: batch/v1
kind: Job
metadata:
  name: delivery-service-migrations
  namespace: dukqa-apps
  labels:
    app: delivery-service
spec:
  template:
    metadata:
      name: delivery-service-migrations
    spec:
      serviceAccountName: delivery-service-sa
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: 746387399274.dkr.ecr.eu-west-1.amazonaws.com/delivery-service:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting DB migrations..."
              /app/scripts/migrate.sh || { echo "Migration failed"; exit 1; }


# (Use this to run DB migrations or pre-start tasks. This example uses a Job-style init—if you prefer an initContainer within the deployment, swap accordingly.)
