apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-support-hpa
  namespace: dukqa-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-support-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

