apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kq-flight-cargo-hpa
  namespace: dukqa-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kq-flight-cargo-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

