apiVersion: v1
kind: ServiceAccount
metadata:
  name: kq-flight-cargo-sa
  namespace: dukqa-apps
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746387399274:role/dukqa-kq-flight-cargo-role

