apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: ec2-apps
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746387399274:role/auth-service-role-dukqa-platform

