apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: insurance-hpa
  namespace: dukqa-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insurance-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

