apiVersion: v1
kind: Pod
metadata:
  name: insurance-init-check
  namespace: dukqa-apps
spec:
  initContainers:
    - name: wait-for-postgres
      image: busybox
      command: ['sh', '-c', 'until nc -z postgres 5432; do echo "waiting for postgres..."; sleep 3; done']
  containers:
    - name: dummy
      image: busybox
      command: ['sh', '-c', 'echo init complete']
  restartPolicy: OnFailure

