apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-sync-workflow
  namespace: argocd
data:
  sync-all.sh: |
    #!/bin/bash
    set -euo pipefail
    
    # Login to ArgoCD
    argocd login argocd-server.argocd.svc.cluster.local:443 \
      --username admin \
      --password "$ARGOCD_PASSWORD" \
      --insecure
    
    # Applications to sync in order
    APPS=("dukqa-global" "dukqa-infra" "dukqa-microservices" "dukqa-ingress" "dukqa-monitoring")
    
    echo "Starting sync of all DukQa applications..."
    
    # Sync all applications
    for app in "${APPS[@]}"; do
      echo "Syncing $app..."
      if argocd app sync "$app" --prune --timeout 300; then
        echo "✅ $app synced successfully"
      else
        echo "❌ Failed to sync $app"
        exit 1
      fi
    done
    
    # Wait for all to be healthy
    echo "Waiting for applications to become healthy..."
    for app in "${APPS[@]}"; do
      echo "Checking health of $app..."
      if argocd app wait "$app" --health --timeout 600; then
        echo "✅ $app is healthy"
      else
        echo "❌ $app failed health check"
        exit 1
      fi
    done
    
    echo "🎉 All applications synced and healthy!"
  
  rollback.sh: |
    #!/bin/bash
    # Rollback to previous version
    APP_NAME=$1
    if [ -z "$APP_NAME" ]; then
      echo "Usage: rollback.sh <app-name>"
      exit 1
    fi
    
    argocd app rollback $APP_NAME
    argocd app wait $APP_NAME --health
    echo "Rollback completed for $APP_NAME"