apiVersion: v1
kind: Secret
metadata:
  name: shipment-secret
  namespace: dukqa-apps
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/shipment"
  API_KEY: "replace_with_real_api_key"

